export const autoPopupCheckUrls = [
  "https://demoguest.com/ukg/ldap",
  "https://demoguest.com/ukg/radius",
  "https://demoguest.com/qa/ukg/ldap",
  "https://demoguest.com/qa/ukg/radius",
  "https://demoguest.com/demo/ukg/ldap",
  "https://demoguest.com/demo/ukg/radius",
  "https://demoguest.com/uat/ukg/ldap",
  "https://demoguest.com/uat/ukg/radius",
  "https://demoguest.com/prod/ukg/ldap",
  "https://demoguest.com/prod/ukg/radius",
  
  "https://demoguest.com/vdi/radius",
  "https://demoguest.com/vdi/ldap",
  "https://demoguest.com/qa/vdi/ldap",
  "https://demoguest.com/qa/vdi/radius",
  "https://demoguest.com/demo/vdi/ldap",
  "https://demoguest.com/demo/vdi/radius",
  "https://demoguest.com/uat/vdi/ldap",
  "https://demoguest.com/uat/vdi/radius",
  "https://demoguest.com/prod/vdi/ldap",
  "https://demoguest.com/prod/vdi/radius",
];